Initial Diet Service
OmerGeva/dishes-api pull request #20
Opened 2023-06-01 09:41 UTC by shacharss

There is a problem with the validator, we need to accept both ints/floats, but can only choose one to validate on. Also the docker compose I have no clue there's a problem there the diet service won't start.

2023-06-01 10:11 UTC, shacharss commented on diets-api/src/exceptions/ninja_exceptions.py
We actually don't need the exceptions here I'll delete it next commit

2023-06-02 09:07 UTC, OmerGeva approved these changes

2023-06-02 09:09 UTC, OmerGeva requested changes
just remove the ninja exceptions and looks good

2023-06-02 12:38 UTC, OmerGeva approved these changes

2023-06-02 12:42 UTC, merged